name: rn_project
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - absl-py=2.1.0=py310h06a4308_0
  - anyio=4.11.0=pyhcf101f3_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py310h7c4b9e2_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.4.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.14.2=pyha770c72_0
  - blas=1.0=mkl
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - brotli-python=1.2.0=py310h8cfb67f_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=1.17.1=py310h8deb56e_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.17=py310h25320af_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h3385a95_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - gettext=0.21.0=hedfda30_2
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.15.1=py310hea18c50_0
  - hdf5=1.14.5=h2b7332f_2
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.1=h6a678d5_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2025.0.0=h06a4308_1171
  - ipykernel=7.1.0=pyha191276_0
  - ipython=8.37.0=pyh8f84b5b_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jansson=2.14=h5eee18b_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py310hff52083_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.10=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - keras=3.11.2=py310h1d409f2_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lark=1.3.1=pyhd8ed1ab_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libcurl=8.16.0=heebcbe5_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgomp=15.2.0=h4751f2c_7
  - libhwloc=2.12.1=default_hf1bbc79_1000
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - libnghttp2=1.67.1=h697f920_0
  - libnsl=2.0.0=h5eee18b_0
  - libsodium=1.0.20=h4ab18f5_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libunistring=1.3=hb25bd0a_0
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - markdown-it-py=4.0.0=py310h06a4308_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mdurl=0.1.2=py310h06a4308_0
  - mistune=3.1.4=pyhcf101f3_0
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py310hacdc0fc_0
  - mkl_fft=2.1.1=py310h8fe796d_0
  - mkl_random=1.3.0=py310h505adc9_0
  - ml_dtypes=0.5.4=py310h23c847b_0
  - mpi=1.0=mpich
  - mpi4py=4.0.3=py310hb6b6513_0
  - mpich=4.3.2=hf345156_0
  - namex=0.1.0=py310h06a4308_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpy-base=2.2.5=py310he1678cf_2
  - openssl=3.6.0=h26f9b46_0
  - optree=0.14.1=py310hdb19cb5_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py310h139afa4_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.19=h6fa692b_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py310h3406613_0
  - pyzmq=27.1.0=py310h4f33d48_0
  - readline=8.3=hc2a1206_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rich=14.2.0=py310h06a4308_0
  - rpds-py=0.29.0=py310hd8f68c5_0
  - scipy=1.15.3=py310h0a862cd_1
  - send2trash=1.8.3=pyh0d859eb_1
  - setuptools=80.9.0=py310h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8=pyhd8ed1ab_0
  - sqlite=3.51.0=h2a70700_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2022.3.0=h698db13_0
  - tbb-devel=2022.3.0=h698db13_0
  - terminado=0.18.1=pyh0d859eb_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.3.0=pyhcf101f3_0
  - tornado=6.5.2=py310h7c4b9e2_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h04d1e81_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h280c20c_3
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - accelerate==1.11.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - click==8.3.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - datasets==4.4.1
      - dill==0.4.0
      - emoji==2.15.0
      - filelock==3.19.1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gast==0.6.0
      - gensim==4.4.0
      - google-pasta==0.2.0
      - greenlet==3.2.4
      - grpcio==1.76.0
      - hf-xet==1.2.0
      - httpx-sse==0.4.3
      - huggingface-hub==0.36.0
      - joblib==1.5.2
      - jsonpatch==1.33
      - kagglehub==0.3.13
      - keras-hub==0.23.0
      - kiwisolver==1.4.9
      - langchain==1.0.7
      - langchain-classic==1.0.0
      - langchain-community==0.4.1
      - langchain-core==1.0.5
      - langchain-text-splitters==1.0.0
      - langgraph==1.0.3
      - langgraph-checkpoint==3.0.1
      - langgraph-prebuilt==1.0.4
      - langgraph-sdk==0.2.9
      - langsmith==0.4.43
      - libclang==18.1.1
      - markdown==3.10
      - markupsafe==2.1.5
      - marshmallow==3.26.1
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - mypy-extensions==1.1.0
      - networkx==3.3
      - nltk==3.9.2
      - numpy==1.26.4
      - nvidia-cublas==13.0.0.19
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti==13.0.48
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc==13.0.48
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime==13.0.48
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cudnn-cu13==9.13.0.50
      - nvidia-cufft==12.0.0.15
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile==1.15.0.42
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand==10.4.0.35
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver==12.0.3.29
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse==12.6.2.49
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-cusparselt-cu13==0.8.0
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nccl-cu13==2.27.7
      - nvidia-nvjitlink==13.0.39
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvshmem-cu13==3.3.24
      - nvidia-nvtx==13.0.39
      - nvidia-nvtx-cu12==12.8.90
      - opt-einsum==3.4.0
      - orjson==3.11.4
      - ormsgpack==1.12.0
      - pandas==2.3.3
      - pillow==11.3.0
      - propcache==0.4.1
      - protobuf==5.29.5
      - pyarrow==22.0.0
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pymupdf==1.26.6
      - pyparsing==3.2.5
      - pypdf==6.3.0
      - python-dotenv==1.2.1
      - regex==2025.11.3
      - requests-toolbelt==1.0.0
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - seaborn==0.13.2
      - sentence-transformers==5.1.2
      - smart-open==7.5.0
      - sqlalchemy==2.0.44
      - sympy==1.14.0
      - tenacity==9.1.2
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.1
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-text==2.19.0
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.9.1+cu130
      - torchaudio==2.9.1+cu130
      - torchvision==0.24.1+cu130
      - tqdm==4.67.1
      - transformers==4.57.1
      - triton==3.5.1
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - werkzeug==3.1.3
      - wrapt==2.0.1
      - xxhash==3.6.0
      - yarl==1.22.0
      - zstandard==0.25.0
prefix: /home/yenreh/anaconda3/envs/rn_project
